x-common: &common-opts
  image: pihole-lists
  build:
    context: .
  stdin_open: true
  tty: true
  environment:
    - LISTS=$LISTS
    - CHECK_DOMAIN_DNS=0
  volumes:
    - ./src:/src:rw
    - ./lists:/src/lists:rw

services:
  #build:
  #  <<: *common-opts
  #  command: >
  #    /bin/bash -c "python -m build"

  cleanup:
    <<: *common-opts
    command: >
      /bin/bash -c "python -m cleanup"
    environment:
      - CHECK_DOMAIN_DNS=0
  #readme:
  #  <<: *common-opts
  #  command: >
  #    /bin/bash -c "python -m readme_list"
